version: "3.8"
volumes:
  db-store:
services:
  web:
    build:
      context: .
      dockerfile: ./infra/docker/php/Dockerfile
    ports:
      - ${WEB_PORT:-80}:80
    volumes:
      - ./backend:/work/backend2
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=${DB_NAME:-laravel_local2}
      - DB_USERNAME=${DB_USER:-phper2}
      - DB_PASSWORD=${DB_PASS:-secret2}

  db:
    build:
      context: .
      dockerfile: ./infra/docker/mysql/Dockerfile
    ports:
      - ${DB_PORT:-3306}:3306
    volumes:
      - db-store:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=${DB_NAME:-laravel_local2}
      - MYSQL_USER=${DB_USER:-phper2}
      - MYSQL_PASSWORD=${DB_PASS:-secret2}
      - MYSQL_ROOT_PASSWORD=${DB_PASS:-secret2}
